# Hierarchical Meta-Policy Integration Test Configuration
# Lightweight config for testing the hierarchical rollout pipeline
# Run: python light_malib/main_psro.py --config expr_configs/hierarchical/5_vs_5_hard/hierarchical_meta_test.yaml

expr_group: gr_football
expr_name: global_hierarchical_meta_test_5_vs_5_hard
log_dir: ./logs
seed: 0
eval_only: False

distributed:
  use: False
  auto_connect:
  auto_copy:
  nodes:
    master:
      ip: "auto"
    workers:      
      - ip:

framework:
  name: "psro"
  max_rounds: 1
  meta_solver: "nash"
  sync_training: True
  stopper:
    type: "win_rate_stopper"
    kwargs:
      min_win_rate: 1.1  # Won't trigger (intentional for test)
      max_steps: 3  # Only 3 iterations for quick test

agent_manager:
  num_agents: 2
  share_policies: False

evaluation_manager:
  num_eval_rollouts: 1  # Minimal for test

policy_data_manager:
  update_func: "gr_football" 
  fields:
    payoff:
      type: "matrix"
      missing_value: -100 
    score:
      type: "matrix"
      missing_value: -100 
    win:
      type: "matrix"
      missing_value: -100 
    lose:
      type: "matrix"
      missing_value: -100 
    my_goal:
      type: "matrix"
      missing_value: -100 
    goal_diff:
      type: "matrix"
      missing_value: -100 
        
monitor:
  type: "remote"  # 'local': tensorboard, 'remote': wandb
  distributed:
    resources:
      num_cpus: 1
      resources:
        - ["node:${distributed.nodes.master.ip}",0.01]

rollout_manager:
  distributed:
    resources:
      num_cpus: 1
      resources:
        - ["node:${distributed.nodes.master.ip}",0.01]
  num_workers: 64  # Minimal workers for quick test
  seed: 12345
  saving_interval: 1
  batch_size: ${rollout_manager.num_workers}
  eval_batch_size: 2
  eval_freq: 1  # Evaluate every iteration
  rollout_metric_cfgs:
    reward:
      type: "sliding"
      window_size: 5
      init_list: [-10000]
    win:
      type: "sliding"
      window_size: 5
      init_list: [0,0,0,0,0]
    policy_switches:
      type: "sliding"
      window_size: 5
      init_list: [0]
  worker:
    distributed:
      resources:
        num_cpus: 1
    rollout_length: 3001                                    # episode length
    eval_rollout_length: 3001          
    sample_length: 0
    padding_length:
    rollout_func_name: "rollout_func_hierarchical"  # Use hierarchical rollout
    episode_mode: 'traj'
    envs:
      - cls: "gr_football"
        id_prefix: "gr_football"
        scenario_config:
          env_name: "benchmark_full_game_5_vs_5_hard"
          number_of_left_players_agent_controls: 4
          number_of_right_players_agent_controls: 1
          representation: "raw"
          rewards: "scoring,checkpoints"
          stacked: False
          logdir: '/tmp/football/hierarchical_test'
          write_goal_dumps: False
          write_full_episode_dumps: False
          render: False
          other_config_options:
            action_set: v2
        reward_config:
          goal_reward: 0
          official_reward: 1
    credit_reassign:
    decaying_exploration:
      init_noise: 0
      total_epoch_to_zero: 1000
      interval: 200

training_manager:
  distributed:
    resources:
      num_cpus: 1
      resources:
        - ["node:${distributed.nodes.master.ip}",0.01]
  master_addr: "127.0.0.1"
  master_port: "12776"  # Different port to avoid conflicts
  local_queue_size: 1
  batch_size: ${rollout_manager.batch_size}
  num_prefetchers: 1
  data_prefetcher:
    distributed:
      resources:
        num_cpus: 1
  num_trainers: 1
  update_interval: 1
  gpu_preload: False  # Disabled for quick test
  trainer:
    distributed:
      resources:
        num_cpus: 1
        num_gpus: 1  # Required by framework (num_trainers <= num_gpus)
        resources:
          - ["node:${distributed.nodes.master.ip}",0.01]
    optimizer: "Adam"
    actor_lr: 3.e-4
    critic_lr: 3.e-4
    opti_eps: 1.e-5
    weight_decay: 0.0
    lr_decay: False
    lr_decay_epoch: 1000

data_server:
  distributed:
    resources:
      num_cpus: 1
      resources:
        - ["node:${distributed.nodes.master.ip}",0.01]
  table_cfg:
    capacity: 100
    sampler_type: "lumrf"
    sample_max_usage: 1
    rate_limiter_cfg:
      min_size: ${training_manager.batch_size}
  read_timeout: 1

policy_server:
  distributed:
    resources:
      num_cpus: 1
      resources:
        - ["node:${distributed.nodes.master.ip}",0.01]

populations:
  - population_id: default
    algorithm:
      name: "HierarchicalMAPPO"
      model_config:
        model: "gr_football.hierarchical"
        initialization:
          use_orthogonal: True
          gain: 1.
        actor:
          network: mlp
          layers:
            - units: 256
              activation: ReLU
            - units: 128
              activation: ReLU
          output:
            activation: False
        critic:
          network: mlp
          layers:
            - units: 256
              activation: ReLU
            - units: 128
              activation: ReLU
          output:
            activation: False

      custom_config:
        num_agents: 4  # Required for MetaActor broadcasting (4 controlled players)
        FE_cfg:
          num_players: 10  # 5v5
          encoder_type: "encoder_global_enhanced"

        # Sub-policies to choose from
        sub_policies:
          - name: "defense_v3"
            path: "light_malib/trained_models/gr_football/5_vs_5/defense_v3"
          - name: "PassingMain_v2"
            path: "light_malib/trained_models/gr_football/5_vs_5/PassingMain_v2"
          - name: "3-1_formation"
            path: "light_malib/trained_models/gr_football/5_vs_5/3-1_formation"
          - name: "3-1_LongPass"
            path: "light_malib/trained_models/gr_football/5_vs_5/3-1_LongPass"

        # Commitment configuration
        commitment:
          mode: "both"
          min_steps: 25
          events: ["possession_change", "game_mode_change"]

        # PPO hyperparameters (same as full config)
        gamma: 0.995
        use_cuda: False  # Must be False - PolicyServer workers don't have GPU access
        use_q_head: False
        ppo_epoch: 20  # Reduced for faster test
        num_mini_batch: 2
        
        return_mode: new_gae
        gae:
          gae_lambda: 0.95
        vtrace:
          clip_rho_threshold: 1.0
          clip_pg_rho_threshold: 100.0

        use_rnn: False
        rnn_layer_num: 1
        rnn_data_chunk_length: 16

        use_feature_normalization: True
        use_popart: True
        popart_beta: 0.99999

        entropy_coef: 0.05
        clip_param: 0.2

      policy_init_cfg:
        agent_0:
          new_policy_ctr_start: -1
          init_cfg:
            - condition: "==0"
              strategy: random
              policy_id: 
              policy_dir:
          initial_policies:

        agent_1:
          new_policy_ctr_start: -1
          init_cfg:
            - condition: "==0"
              strategy: pretrained
              policy_id: built_in
              policy_dir: light_malib/trained_models/gr_football/5_vs_5/built_in
          initial_policies:

